import React from 'react';
import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { CTASection, PageHero, ReelsSection, SectionHeading } from '../components.jsx';
import { client, images, isNaaee, mapsHref } from '../data.js';

export default function Reviews() { return <main><PageHero image={images.beauty} eyebrow="Customer stories" title={isNaaee ? <>Ratings and<br/><em>reviews.</em></> : <>Real people.<br/><em>Real results.</em></>} subtitle={isNaaee ? 'Review details supplied for NAAEE SALON.' : 'The best stories are told by the people who lived them.'} className="hero-reviews"/>
  <div className="reviews-rating-band"><div className="container reviews-rating-inner"><div><span className="eyebrow">The word around Jaipur</span><strong>{client.rating}</strong><span className="reviews-stars" aria-hidden="true">★★★★★</span><span className="reviews-rating-caption">{isNaaee ? `${client.reviews} reviews` : 'Google rating*'}</span></div><a className="text-link" href={mapsHref} target="_blank" rel="noreferrer">{isNaaee ? 'Find NAAEE SALON' : 'Explore Google reviews'} <ArrowRight size={16}/></a></div></div>
  <section className="section-pad container"><div className="intro-layout"><div><span className="eyebrow">From our community</span><h2>Every look has<br/><em>a story.</em></h2></div><div><p>{isNaaee ? 'NAAEE SALON has a supplied rating of 4.9/5 and 141+ reviews. Individual review text has not been provided.' : 'We would love to share genuine customer experiences here. Verified reviews, before and after photos, and customer videos can be added when provided by Uplooks.'}</p><p className="content-note">Customer review content coming soon. The photographs on this page are illustrative.</p><Link className="text-link" to="/gallery">Explore the gallery <ArrowRight size={16}/></Link></div></div></section>
  <section className="section-pad soft-section"><div className="container"><SectionHeading eyebrow="Customer moments" title={isNaaee ? 'Illustrative previews' : 'Looks worth sharing'} description={isNaaee ? 'Example imagery until NAAEE SALON photos are available.' : 'A preview of how real customer photos and transformation stories will appear.'}/><div className="results-grid"><div className="result result-large"><img src={images.bridal} alt={isNaaee ? 'Illustrative beauty look' : 'Illustrative bridal look'} loading="lazy"/><span>{isNaaee ? 'Beauty services' : 'Bridal moments'}</span></div><div className="result"><img src={images.mens} alt={isNaaee ? 'Illustrative hair look' : "Illustrative men's look"} loading="lazy"/><span>{isNaaee ? 'Hair services' : 'Grooming moments'}</span></div><div className="result"><img src={images.beauty} alt="Illustrative beauty look" loading="lazy"/><span>Beauty moments</span></div></div></div></section>
  <ReelsSection compact/><p className="rating-disclosure">{isNaaee ? 'Rating and review count supplied for NAAEE SALON; no individual testimonials have been added.' : '*Rating supplied by Uplooks; confirm the live Google listing before publication.'}</p><CTASection />
</main>; }
